### ISSUE TITLE
Using sabre/dav feels wrong

### ISSUE THREAD

**Issue by phoenixgao** [thephpleague/flysystem-webdav#10]
As I remember sabre/dav is an entire dav server framework with an experimental dav client

is it really good to use it?

also it doesn't support stream, may be extending guzzle/http with dav methods cound be a better idea?

**Comment by frankdejonge** [comment]
@phoenixgao there's a lot more to webdav besides http requests, which is so specific to webdav I don't intent to reimplement that.
