### ISSUE TITLE
Missing Header

### ISSUE THREAD

**Issue by joshwegener** [thephpleague/flysystem-webdav#18]
I'm using this to connect with OpenDrive, and for some reason they don't send back "last-modified" sometimes. For example, when reading a file, their is no header for "last-modified" so it crashes at line 94 when it's trying to get the timestamp. Can this be modified to to check for that header before using it?

**Comment by pboethig** [comment]
What is the current state of this issue?

**Comment by EchoCompanyK** [comment]
in end of 2021 the issue is present (cloud.mail.ru not send last-modified in download file)

![2021-12-31_13-59-24](https://user-images.githubusercontent.com/72492140/147813811-d7befadd-b83a-4181-8dfd-4b0073c07915.png)

**Comment by frankdejonge** [comment]
fixed in 1.1.10
