### ISSUE TITLE
\Sabre\HTTP\ClientHttpException is not caught in WebDAVAdapter->getMetadata() method

### ISSUE THREAD

**Issue by vleukhin** [thephpleague/flysystem-webdav#20]
My WebDAV service returns http 404 code when file does not exist (it's ok), so _**Sabre\DAV\Client**_ throws **_\Sabre\HTTP\ClientHttpException_** but _**League\Flysystem\WebDAV\WebDAVAdapter->getMetadata()**_ method catchs only **_Sabre\DAV\Exception_**.

**Comment by derjaeckel** [comment]
Yes, i have the same problem.

I think it depends on that 

 - ClientHttpException extends from \Exception
 - Exception extends from \Exception

But in the catch condition it matches only `Exception` not `\Exception`, and so on respectively NOT `ClientHttpException`

**Comment by khanhicetea** [comment]
I met a same problem, could we fix this problem asap ?

**Comment by khanhicetea** [comment]
👍 Thank you very much for the hotfix, it works like a charm now

**Comment by frankdejonge** [comment]
@khanhicetea welcome :)
