### ISSUE TITLE
Webdav icm owncloud, setup

### ISSUE THREAD

**Issue by arnovr** [thephpleague/flysystem-webdav#25]
When using owncloud the webdav url is:
https://owncloud.com/remote.php/webdav/

My first take was the sabre dav client to have base uri:
"https://owncloud.com/remote.php/webdav/"
and flysystem having an emtpy prefix

When calling:
```
$filesystem->listContents('/');
```
It will try to retrieve PROPFID https://owncloud.com/ and ignores remote.php/webdav.

What does work is:
sabredav baseUri https://owncloud.com
and giving flysystem the prefix: "remote.php/webdav"

Is this intended behavior?

**Comment by frankdejonge** [comment]
@arnovr iirc that's how the underlying lib works, so yeah.

**Comment by arnovr** [comment]
Allright, never mind then
