### ISSUE TITLE
Memory_limit issue

### ISSUE THREAD

**Issue by ovidiul** [thephpleague/flysystem-webdav#28]
I was trying to upload a 150MB file to yandex using webdav, and it seems i get this error

[2017-03-05 10:19:08] php_system.INFO: E_ERROR: array ( 'type' => 1, 'message' => 'Allowed memory size of 77594624 bytes exhausted (tried to allocate 156996369 bytes)', 'file' => '/home/thinkovi/public_html/wp-content/plugins/xcloner-backup-and-restore/vendor/league/flysystem/src/Adapter/Polyfill/StreamedWritingTrait.php', 'line' => 23, ) [] []

when calling this method updateStream()

after further debugging, it seems the method stream from Polyfill/StreamedWritingTrait.php tries to get the file content using stream_get_contents which will usually run into php memory_limit issues on large files.

It seems sabre accepts the file resource instead as the file contents to avoid large file uploads memory_limit, so the line

`$contents = stream_get_contents($resource);
`

is not necessary, the $resource can be passed directory to the callback method as

`return call_user_func($fallbackCall, $path, $resource, $config);
`

I have added this method to the WebDAVAdapter.php file

```
protected function stream($path, $resource, Config $config, $fallback){
	Util::rewindStream($resource);
        $fallbackCall = [$this, $fallback];

        return call_user_func($fallbackCall, $path, $resource, $config);
	}_
```

to  fix the issue

**Comment by frankdejonge** [comment]
This was fixed in a PR.
