### ISSUE TITLE
laravel webdav options

### ISSUE THREAD

**Issue by gaalgergely** [thephpleague/flysystem-webdav#31]
Hello!
How can I set two webdav connections in laravel? The .env file contains one opportunity, but I need more.

**Comment by gaalgergely** [comment]
In case you want to use it a Controller file:
Add this to the top of the file:
`use League\Flysystem\Filesystem;
use League\Flysystem\WebDAV\WebDAVAdapter;
use Sabre\DAV\Client;`
then to the action:
`$settings = [
            'baseUri' => env('BB_URL'),
            'userName' => env('BB_USERNAME'),
            'password' => env('BB_PASSWORD')
        ];
        $client = new Client($settings);
        $adapter = new WebDAVAdapter($client,'');
        $flysystem = new Filesystem($adapter);`
Then you have your $flysystem varible configured by the env file.

**Comment by frankdejonge** [comment]
@gaalgergely thanks for coming back to this, for a "tighter" integration I suggest opening an issue or a PR with the laravel repo to get a config based integration.
