### ISSUE TITLE
Memory limit when trying to upload large file

### ISSUE THREAD

**Issue by gasparyanyur** [thephpleague/flysystem-webdav#34]
I have tried to upload large file to another host, but the response I have got the following error
>Allowed memory size of 134217728 bytes exhausted (tried to allocate 31860068 bytes) in Client.php on line 494

I have already seen the [Memory_limit issue #28](https://github.com/thephpleague/flysystem-webdav/issues/28) but its doesn't work for me

Here is my logic to upload file to another host 

```
     try {
           $stream = $file->readStream();
           $file->setStorage( $storage->id );
           $file->storage()->getDriver()->putStream( $file->getRealDestination(), $stream );
            $file->putStream( $file->getRealDestination(), $stream );
      } catch( \Exception $e ) {
           $file->setStorage( $storage->id );
      }
```

I have tried to change 352,353 lines in Sabre\HTTP\Client  to 
```
$response = $this->curlExec($this->curlHandle);
$stream = fopen('php://memory','r+');
fwrite($stream, $response);
rewind($stream);
$response = $this->parseCurlResult($stream, $this->curlHandle);
```

and 494,498 lines to 
```
$headerBlob = stream_get_contents($response, 0, $curlInfo['header_size']);
$responseBody = stream_get_contents($response, $curlInfo['header_size']) ?: null;
```

but it also not working...

**Comment by frankdejonge** [comment]
This was fixed in a PR.
