### ISSUE TITLE
Connect to webDAV via SSO

### ISSUE THREAD

**Issue by mehrdaad** [thephpleague/flysystem-webdav#35]
Is it possible to connect to a webdav client via sso?  
I might be missing some concepts here, but AFAIK it's possible to connect to a webDAV client via a sso token.  
Can you guide me here?

**Comment by frankdejonge** [comment]
If possible it should be configured in the `sabre/dav` package, we only consume the webdav part, not the authentication.

**Comment by mehrdaad** [comment]
@frankdejonge I can confirm that webdav SSO authentication is not supported in ``sabre/dav`` yet. [reference](https://github.com/nextcloud/server/issues/7062#issuecomment-342416653)
