### ISSUE TITLE
Sabre DAV doesn't follow semver

### ISSUE THREAD

**Issue by patkar** [thephpleague/flysystem-webdav#5]
Sabre DAV doesn't follow semver. A minor release (according to semver) is as major release in Sabre DAV. See Versioning scheme at http://sabre.io/dav/upgrading/

With this in mind, for which version the adapter was build? 2.0 or 2.1?

**Comment by patkar** [comment]
Meeh, even with a 2.0.x release writing doesn't work. Should the adapter fixed to ~2.1.0 at the moment and make it work with this version?

**Comment by frankdejonge** [comment]
We've updated to 3.1.
