### ISSUE TITLE
listContents with recursive=true does not work

### ISSUE THREAD

**Issue by mmaerklin** [thephpleague/flysystem-webdav#53]
Hi,
I'm using the WebDAV adapter to recursively list the contents of an ownCloud server. However, I receive only the files and directories on the first level of the search path.

From looking at the source code (line 283 in WebDAVAdapter.php) it appears that param _recursive_ is not evaluated and _propFind_ is always called with param "1".  According to http://webdav.org/specs/rfc4918.html#HEADER_Depth the correct value should be "infinity".

A quick hack on my side seems to support this assumption. Can you take a look at that?

And by the way: Thanks a lot for providing this very useful package!

**Comment by mmaerklin** [comment]
In the meantime I did realize, that listContents is called repeatedly to fetch all sub directories. The problem seems to be that directories are not recognised, because the WebDAV XML property _iscollection_ is not found (and _displayname_ neither, by the way). Also, from looking at http://webdav.org/specs/rfc4918.html, _iscollection_ does not seem to be a valid property anyway.

http://webdav.org/specs/rfc4918.html#collection.resources seems to imply, that collections could be identified by a trailing slash in its path.

**Comment by kesselb** [comment]
Ref: https://github.com/nextcloud/server/issues/16267

**Comment by kesselb** [comment]
http://webdav.org/specs/rfc4918.html#PROPERTY_resourcetype 

I read the rfc like this: A collection has an element resourcetype with an empty collection element as child. 

Does that make sense?
