### ISSUE TITLE
curl_exec(): CURLOPT_INFILE resource has gone away, resetting to default

### ISSUE THREAD

**Issue by RosiersRobin** [thephpleague/flysystem-webdav#55]
I want to be able to upload multiple (dynamic) files (pdf).

So I have the following lay-out:

[![https://i.imgur.com/TLk3dvv.png][1]][1]

As you can see, the form has 4 input fields for files, but it also has 2 text fields and for every file upload row, it has a checkbox. The "flow" is the following:

1. Add title and year
2. Check the classes (Initiatie, Recreatie, Toersime, and Sport) you want to enable (and upload a PDF for)
3. Upload 1 PDF file per class.

The files are PDF files (1 per class). I tried the following code in PHP to upload the files, but I can only upload one, sometimes 2 files at a time, depending on how large the files are.

    public function postGapersritAddResults(Request $request): RedirectResponse
    {
        // Handle upload
        $path = 'documents/gapersrit/'.$request->get('year').'/results';
    
        foreach (['initiatie', 'recreatie', 'toerisme', 'sport'] as $item) {
            if ($request->hasFile('file_'.$item)) {
                $request->file('file_'.$item)->storeAs($path, $item.'.'.$request->file('file_'.$item)->getClientOriginalExtension(), 'webdav');
            }
        }
    
        // Handle database
        $result = new SiteGapersritResults();
        $result->title = $request->get('title');
        $result->year = $request->get('year');
        $result->initiatie =  filter_var($request->get('active_initiatie'), FILTER_VALIDATE_BOOLEAN);
        $result->recreatie =  filter_var($request->get('active_recreatie'), FILTER_VALIDATE_BOOLEAN);
        $result->toerisme =  filter_var($request->get('active_toerisme'), FILTER_VALIDATE_BOOLEAN);
        $result->sport =  filter_var($request->get('active_sport'), FILTER_VALIDATE_BOOLEAN);
        $result->save();
    
        toastr()->success('Saved the results for year '.$result->year.'.', 'Success', ['timeOut' => 5000]);
        return redirect()->to('admin/gapersrit/results');
    }

If someone has a better idea of how I could do this, please help me out.
Ideally, I want to select all the files and be able to upload them one by one (like in my code), but for some reason, this doesn't work and throws most of the time the too large error, however, I guess I'm uploading one file at a time?

The limit for upload sizes is 100M in php.ini and my Nginx configuration.

I get the following error on my current code:

`curl_exec(): CURLOPT_INFILE resource has gone away, resetting to default`

full trace: https://pastebin.com/rqUeEhGa

  [1]: https://i.stack.imgur.com/tS4zB.png

**Comment by frankdejonge** [comment]
Seems more likely that this issue should be handled by the sabre/dav team. We don't use curl, that package does.

**Comment by roxblnfk** [comment]
@RosiersRobin can u try this code on version [1.0.5](https://github.com/thephpleague/flysystem-webdav/tree/1.0.5) ? I suspect something has broken after this version

**Comment by RosiersRobin** [comment]
This is what my composer install gives me:

![result](https://i.imgur.com/DMF100W.png)

**Comment by roxblnfk** [comment]
@RosiersRobin `composer require league/flysystem-webdav 1.0.5`

**Comment by RosiersRobin** [comment]
That just fixed it, so maybe when I have time, I'll compare these and try to fix it with a PR.
