### ISSUE TITLE
Necessary data rewind wasn't possible

### ISSUE THREAD

**Issue by silas229** [thephpleague/flysystem-webdav#71]
Hi,
when I want to save a file I get following cURL error message (Code [65](https://curl.se/libcurl/c/libcurl-errors.html#:~:text=CURLE_SEND_FAIL_REWIND%20(65),rewinding%20operation%20failed.)):
`Sabre\HTTP\ClientException with message 'necessary data rewind wasn't possible'`

My implementation:

`AppServiceProvider@boot`
```php
\Storage::extend('webdav', function ($app, $config) {
    $client = new WebDAVClient($config['login']);

    $client->addCurlSetting(CURLOPT_VERBOSE, true); // Debug

    return new Filesystem(new WebDAVAdapter($client));
});
```

`config/filesystems.php`
```php
return [
        'webdav' => [
            'driver'     => 'webdav',
            'login'      => [
                'baseUri'  => env('WEBDAV_BASE_URI'),
                'userName' => env('WEBDAV_USER'),
                'password' => env('WEBDAV_PASSWORD'),
                'proxy'    => env('WEBDAV_PROXY', false),
            ],
            'root'       => env('BITRIX_WEBDAV_BASE_URI'),
            'url'        => env('APP_URL') . '/storage/uploads',
            'visibility' => 'private',
        ],
];
```

Code in Artisan Tinker:
```php
Storage::disk('webdav')->putFile('test', 'file.txt');
```

I tried it with several WebDAV Servers and several implementations in my code. It always fails with the same error message.

<details>
<summary>Verbose log:</summary>

* Trying xxx.xxx.xxx:443...
* Connected to example.net (xxx.xxx.xxx) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
*  CAfile: /usr/local/etc/openssl@1.1/cert.pem
*  CApath: none
* SSL connection using TLSv1.3 / TLS_AES_256_GCM_SHA384
* ALPN, server accepted to use h2
* Server certificate:
*  subject: CN=example.net
*  start date: Nov  5 22:00:20 2021 GMT
*  expire date: Feb  3 22:00:19 2022 GMT
*  subjectAltName: host "example.net" matched cert's "example.net"
*  issuer: C=US; O=Let's Encrypt; CN=R3
*  SSL certificate verify ok.
* Using HTTP2, server supports multiplexing
* Connection state changed (HTTP/2 confirmed)
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
* Using Stream ID: 1 (easy handle 0x7f8fdf80e200)
> PROPFIND /docs/path/test/7SPrUysgrAjxZXNncjMx1NLvvGVbO4nROgY8LReE.txt HTTP/2
Host: example.net
user-agent: sabre-dav/4.3.0 (http://sabre.io/)
accept: */*
depth: 0
content-type: application/xml
content-length: 244

* We are completely uploaded and fine
* old SSL session ID is stale, removing
* Connection state changed (MAX_CONCURRENT_STREAMS == 128)!
< HTTP/2 401 
< server: nginx
< date: Tue, 04 Jan 2022 13:46:42 GMT
< content-type: text/html; charset=UTF-8
< content-length: 0
< vary: HTTPS
< set-cookie: PHPSESSID=xxxxxxxxxxxxxxxxxxxxx; path=/; HttpOnly
< expires: Thu, 19 Nov 1981 08:52:00 GMT
< cache-control: no-store, no-cache, must-revalidate
< pragma: no-cache
< x-webdav-status: 401 Unauthorized
< www-authenticate: Digest realm="xxxxxxxxxx", nonce="xxxxxxxxxx"
< 
* Connection #0 to host example.net left intact
* Issue another request to this URL: 'https://example.net/docs/path/test/7SPrUysgrAjxZXNncjMx1NLvvGVbO4nROgY8LReE.txt'
* Found bundle for host example.net: 0x7f8fdd536fc0 [can multiplex]
* Re-using existing connection! (#0) with host example.net
* Connected to example.net (xxx.xxx.xxx) port 443 (#0)
* Server auth using Digest with user 'xxxxxxxxxx'
* Using Stream ID: 3 (easy handle 0x7f8fdf80e200)
> PROPFIND /docs/path/test/7SPrUysgrAjxZXNncjMx1NLvvGVbO4nROgY8LReE.txt HTTP/2
Host: example.net
authorization: Digest username="xxxxxxxxxx", realm="xxxxxxxxxx", nonce="xxxxxxxxxx", uri="/docs/path/test/7SPrUysgrAjxZXNncjMx1NLvvGVbO4nROgY8LReE.txt", response="xxxxxxxxxx"
user-agent: sabre-dav/4.3.0 (http://sabre.io/)
accept: */*
depth: 0
content-type: application/xml
content-length: 244

* We are completely uploaded and fine
< HTTP/2 404 
< server: nginx
< date: Tue, 04 Jan 2022 13:46:42 GMT
< content-type: text/html;charset=UTF-8
< content-length: 278
< vary: HTTPS
< set-cookie: PHPSESSID=xxxxxxxxxxxxxxxxxxxxx; path=/; HttpOnly
< expires: Thu, 19 Nov 1981 08:52:00 GMT
< cache-control: no-store, no-cache, must-revalidate
< pragma: no-cache
< x-webdav-status: 404 Not Found
<
* Connection #0 to host example.net left intact
* Found bundle for host example.net: 0x7f8fdd536fc0 [can multiplex]
* Re-using existing connection! (#0) with host example.net
* Connected to example.net (xxx.xxx.xxx) port 443 (#0)
* Using Stream ID: 5 (easy handle 0x7f8fdf80e200)
> PROPFIND /docs/path/test HTTP/2
Host: example.net
user-agent: sabre-dav/4.3.0 (http://sabre.io/)
accept: */*
depth: 0
content-type: application/xml
content-length: 244

* We are completely uploaded and fine
< HTTP/2 401 
< server: nginx
< date: Tue, 04 Jan 2022 13:46:42 GMT
< content-type: text/html; charset=UTF-8
< content-length: 0
< vary: HTTPS
< set-cookie: PHPSESSID=xxxxxxxxxxxxxxxxxxxxx; path=/; HttpOnly
< expires: Thu, 19 Nov 1981 08:52:00 GMT
< cache-control: no-store, no-cache, must-revalidate
< pragma: no-cache
< x-webdav-status: 401 Unauthorized
< www-authenticate: Digest realm="xxxxxxxxxx", nonce="xxxxxxxxxx"
< 
* Connection #0 to host example.net left intact
* Issue another request to this URL: 'https://example.net/docs/path/test'
* Found bundle for host example.net: xxxxxxxxxx [can multiplex]
* Re-using existing connection! (#0) with host example.net
* Connected to example.net (xxx.xxx.xxx) port 443 (#0)
* Server auth using Digest with user 'xxxxxxxxxx'
* Using Stream ID: 7 (easy handle 0x7f8fdf80e200)
> PROPFIND /docs/path/test HTTP/2
Host: example.net
authorization: Digest username="xxxxxxxxxx", realm="xxxxxxxxxx", nonce="xxxxxxxxxx", uri="/docs/path/test", response="xxxxxxxxxx"
user-agent: sabre-dav/4.3.0 (http://sabre.io/)
accept: */*
depth: 0
content-type: application/xml
content-length: 244

* We are completely uploaded and fine
< HTTP/2 404 
< server: nginx
< date: Tue, 04 Jan 2022 13:46:42 GMT
< content-type: text/html;charset=UTF-8
< content-length: 233
< vary: HTTPS
< set-cookie: PHPSESSID=xxxxxxxxxxxxxxxxxxxxx; path=/; HttpOnly
< expires: Thu, 19 Nov 1981 08:52:00 GMT
< cache-control: no-store, no-cache, must-revalidate
< pragma: no-cache
< x-webdav-status: 404 Not Found
<
* Connection #0 to host example.net left intact
* Found bundle for host example.net: 0x7f8fdd536fc0 [can multiplex]
* Re-using existing connection! (#0) with host example.net
* Connected to example.net (xxx.xxx.xxx) port 443 (#0)
* Using Stream ID: 9 (easy handle 0x7f8fdf80e200)
> MKCOL /docs/path/test/ HTTP/2
Host: example.net
user-agent: sabre-dav/4.3.0 (http://sabre.io/)
accept: */*
content-length: 0
content-type: application/x-www-form-urlencoded

< HTTP/2 401 
< server: nginx
< date: Tue, 04 Jan 2022 13:46:42 GMT
< content-type: text/html; charset=UTF-8
< content-length: 0
< vary: HTTPS
< set-cookie: PHPSESSID=xxxxxxxxxxxxxxxxxxxxx; path=/; HttpOnly
< expires: Thu, 19 Nov 1981 08:52:00 GMT
< cache-control: no-store, no-cache, must-revalidate
< pragma: no-cache
< x-webdav-status: 401 Unauthorized
< www-authenticate: Digest realm="xxxxxxxxxx", nonce="xxxxxxxxxx"
< 
* Connection #0 to host example.net left intact
* Issue another request to this URL: 'https://example.net/docs/path/test/'
* Found bundle for host example.net: xxxxxxxxxx [can multiplex]
* Re-using existing connection! (#0) with host example.net
* Connected to example.net (xxx.xxx.xxx) port 443 (#0)
* Server auth using Digest with user 'xxxxxxxxxx'
* Using Stream ID: b (easy handle 0x7f8fdf80e200)
> MKCOL /docs/path/test/ HTTP/2
Host: example.net
authorization: Digest username="xxxxxxxxxx", realm="xxxxxxxxxx", nonce="xxxxxxxxxx", uri="/docs/path/test/", response="86223360a7dad37e6fe2d3625eb1fcbc"
user-agent: sabre-dav/4.3.0 (http://sabre.io/)
accept: */*
content-length: 0
content-type: application/x-www-form-urlencoded

< HTTP/2 201 
< server: nginx
< date: Tue, 04 Jan 2022 13:46:43 GMT
< content-type: text/html; charset=UTF-8
< content-length: 0
< vary: HTTPS
< set-cookie: PHPSESSID=xxxxxxxxxxxxxxxxxxxxx; path=/; HttpOnly
< expires: Thu, 19 Nov 1981 08:52:00 GMT
< cache-control: no-store, no-cache, must-revalidate
< pragma: no-cache
< x-webdav-status: 201 Created
< location: https://example.net:443/docs/path/test/
< x-content-type-options: nosniff
< x-frame-options: SAMEORIGIN
< 
* Connection #0 to host example.net left intact
* Found bundle for host example.net: xxxxxxxxxx [can multiplex]
* Re-using existing connection! (#0) with host example.net
* Connected to example.net (xxx.xxx.xxx) port 443 (#0)
* Using Stream ID: d (easy handle 0x7f8fdf80e200)
> PUT /docs/path/test/7SPrUysgrAjxZXNncjMx1NLvvGVbO4nROgY8LReE.txt HTTP/2
Host: example.net
user-agent: sabre-dav/4.3.0 (http://sabre.io/)
accept: */*
content-length: 291

* We are completely uploaded and fine
< HTTP/2 401 
< server: nginx
< date: Tue, 04 Jan 2022 13:46:43 GMT
< content-type: text/html; charset=UTF-8
< content-length: 0
< vary: HTTPS
< set-cookie: PHPSESSID=xxxxxxxxxxxxxxxxxxxxx; path=/; HttpOnly
< expires: Thu, 19 Nov 1981 08:52:00 GMT
< cache-control: no-store, no-cache, must-revalidate
< pragma: no-cache
< x-webdav-status: 401 Unauthorized
< www-authenticate: Digest realm="xxxxxxxxxx", nonce="xxxxxxxxxx"
* necessary data rewind wasn't possible
* stopped the pause stream!
* Connection #0 to host example.net left intact
Sabre\HTTP\ClientException with message 'necessary data rewind wasn't possible'
*** Execution finished ***
</details>

**Comment by silas229** [comment]
Any idea @frankdejonge ?

**Comment by frankdejonge** [comment]
@silas229 no clue to be honest, could be a problem with sabre/dav perhaps?

**Comment by impronta48** [comment]
I've solved this adding 
$settings['authType'] = 1; //Basic authentication

(found in https://stackoverflow.com/a/72365650/3813117)
