### ISSUE TITLE
Method `has` throws an exception if the file does not exists

### ISSUE THREAD

**Issue by adeons** [thephpleague/flysystem-webdav#8]
The method `has` calls `getMetadata`, which in turn calls `Sabre\DAV\Client::propFind`. The last one, seems to throw a `Sabre\DAV\Exception` if the specified file does not exists.

Replace `Exception\FileNotFound` with `\Sabre\DAV\Exception` at line 63 to fix the issue.

**Comment by lahaxearnaud** [comment]
This issue fixed by https://github.com/thephpleague/flysystem-webdav/pull/7
